# -*- coding: utf-8 -*-
#  author: ict
import json

a = {'questions': [{'type': 'single_choice',
                    'question_text': '根据《银行业从业人员职业操守和行为准则》，以下哪类人员不属于本准则适用范围？',
                    'options': [{'id': 'A', 'text': '境内银行业金融机构的正式员工', 'is_correct': False,
                                 'explanation': '根据第二条，境内银行业金融机构工作的人员属于本准则适用对象。'},
                                {'id': 'B', 'text': '被委派至境外分支机构工作的银行员工', 'is_correct': False,
                                 'explanation': '第二条明确规定，委派到国（境）外分支机构、控（参）股公司工作的人员应当适用本准则。'},
                                {'id': 'C', 'text': '银行外包服务公司的非派驻人员', 'is_correct': True,
                                 'explanation': '本准则适用于银行业金融机构及其委派人员，不包括外包公司中未被委派至银行岗位的普通外包人员。'},
                                {'id': 'D', 'text': '劳务派遣至银行业协会的工作人员', 'is_correct': False,
                                 'explanation': '第五十一条规定，银行业协会的工作人员及劳务派遣人员参照适用本准则。'}],
                    'overall_explanation': '根据《准则》第二条和第五十一条，适用对象包括境内银行员工、境外委派人员以及银行业协会的劳务派遣人员，但不包括与银行无直接劳动或委派关系的第三方外包公司普通员工。'},
                   {'type': 'single_choice',
                    'question_text': '银行业从业人员在发现所在机构存在侵害国家金融安全的违法行为时，应当如何处理？',
                    'options': [{'id': 'A', 'text': '保持沉默，避免影响同事关系', 'is_correct': False,
                                 'explanation': '保持沉默违反了职业操守，从业人员有责任揭露违法行为。'},
                                {'id': 'B', 'text': '仅向直接上级口头汇报', 'is_correct': False,
                                 'explanation': '口头汇报不够正式，且可能无法有效推动问题解决。'},
                                {'id': 'C', 'text': '有权向上级机构或监管机构直至国家司法机关举报', 'is_correct': True,
                                 'explanation': '第四十四条规定，从业人员有权向上级机构、监督管理部门直至国家司法机关举报违法行为。'},
                                {'id': 'D', 'text': '在社交媒体上公开曝光', 'is_correct': False,
                                 'explanation': '擅自对外发布信息违反第四十六条关于信息发布的规定，可能造成舆情风险。'}],
                    'overall_explanation': '根据第四十四条，从业人员对机构违法行为有揭露责任，并可通过正式渠道向上举报，但不得擅自对外公开传播。'},
                   {'type': 'single_choice',
                    'question_text': '关于银行业从业人员处理客户信息的行为，以下哪项是符合《准则》要求的？', 'options': [
                       {'id': 'A', 'text': '离职后可带走原客户的联系方式用于新工作', 'is_correct': False,
                        'explanation': '违反第二十五条和第三十八条，禁止擅自带走客户资源和泄露客户信息。'},
                       {'id': 'B', 'text': '为提升服务效率，可将客户资料存入个人云盘备份', 'is_correct': False,
                        'explanation': '违反第九条和第三十八条，严禁违规存储或泄露客户隐私信息。'},
                       {'id': 'C', 'text': '在受雇期间和离职后均不得违规泄露客户信息', 'is_correct': True,
                        'explanation': '第三十八条明确规定，从业人员在受雇期间及离职后均不得违反规定泄露客户资料和交易信息。'},
                       {'id': 'D', 'text': '经客户口头同意即可向第三方共享其信用记录', 'is_correct': False,
                        'explanation': '客户信息共享需符合法律法规和机构规定，仅口头同意不足以构成合规依据。'}],
                    'overall_explanation': '第三十八条强调客户信息保护的持续性义务，无论在职或离职，均不得违规泄露客户资料。'},
                   {'type': 'single_choice', 'question_text': '下列哪项行为最符合‘专业胜任’的职业操守要求？',
                    'options': [{'id': 'A', 'text': '依靠经验办理业务，无需关注新政策', 'is_correct': False,
                                 'explanation': '违反第六条，专业胜任要求持续学习政策法规和业务知识。'},
                                {'id': 'B', 'text': '仅完成本职工作，不参与培训', 'is_correct': False,
                                 'explanation': '未体现终身学习理念，不符合专业胜任的精神。'},
                                {'id': 'C', 'text': '主动学习反洗钱新规并应用于客户尽职调查', 'is_correct': True,
                                 'explanation': '第六条要求从业人员不断学习提高政策法规和风险管控水平，此行为符合要求。'},
                                {'id': 'D', 'text': '将复杂业务推给同事处理', 'is_correct': False,
                                 'explanation': '逃避职责，未能体现专业能力提升和履职尽责。'}],
                    'overall_explanation': '专业胜任要求从业人员具备专业知识和技能，并通过持续学习提升能力，主动应用新知识于实际工作是其体现。'},
                   {'type': 'single_choice',
                    'question_text': '根据《准则》，银行业高级管理人员在职业行为中的特殊责任是什么？', 'options': [
                       {'id': 'A', 'text': '可以享受特殊待遇以体现职位尊贵', 'is_correct': False,
                        'explanation': '违反第二十六、三十三条关于勤俭节约和反‘四风’的要求。'},
                       {'id': 'B', 'text': '只需遵守普通员工的职业操守', 'is_correct': False,
                        'explanation': '第五十条明确高管应带头遵守、模范践行，并以上率下。'},
                       {'id': 'C', 'text': '应当带头遵守、以上率下，推动机构营造良好的从业氛围', 'is_correct': True,
                        'explanation': '第五十条规定高管应通过‘立规矩、讲规矩、守规矩’以上率下，全面推动良好氛围建设。'},
                       {'id': 'D', 'text': '可豁免部分行为规范以提高决策效率', 'is_correct': False,
                        'explanation': '所有从业人员均须遵守《准则》，高管不得豁免。'}],
                    'overall_explanation': '第五十条明确高管不仅要遵守准则，还应发挥示范作用，在战略和管理中融入职业操守要求，引领机构文化建设。'},
                   {'type': 'multiple_choice',
                    'question_text': '根据《准则》，以下哪些行为属于严禁的信息领域违法犯罪行为？', 'options': [
                       {'id': 'A', 'text': '利用职务便利窃取客户信息', 'is_correct': True,
                        'explanation': '第十四条明确禁止利用职务便利实施窃取、泄露客户信息等行为。'},
                       {'id': 'B', 'text': '发现信息泄露后立即报告并采取措施', 'is_correct': False,
                        'explanation': '这是合规行为，符合第十四条中‘发现泄密事件应及时报告’的要求。'},
                       {'id': 'C', 'text': '将所在机构的商业秘密泄露给亲友', 'is_correct': True,
                        'explanation': '第十四条禁止泄露所在机构商业秘密，无论对象是否为亲友。'},
                       {'id': 'D', 'text': '使用公司邮箱发送工作相关文件', 'is_correct': False,
                        'explanation': '正常使用公司邮箱属于合规行为，不构成信息违法。'},
                       {'id': 'E', 'text': '未经授权访问其他部门的客户数据库', 'is_correct': True,
                        'explanation': '属于越权获取信息，违反第九条和第十四条关于严守秘密和信息保护的规定。'}],
                    'overall_explanation': '第十四条严禁利用职务便利窃取、泄露客户信息和商业秘密，未经授权访问、向他人泄露均属违规。及时报告泄密是合规义务，而非禁止行为。'},
                   {'type': 'multiple_choice', 'question_text': '银行业从业人员在销售业务中，哪些行为是被明确禁止的？',
                    'options': [{'id': 'A', 'text': '销售未经所在机构审批的产品', 'is_correct': True,
                                 'explanation': '第二十条禁止销售或推介未经机构审批的产品。'},
                                {'id': 'B', 'text': '向客户充分提示产品风险', 'is_correct': False,
                                 'explanation': '第三十九条规定必须充分披露风险，这是合规要求。'},
                                {'id': 'C', 'text': '为特定客户非公开销售优于其他客户的理财产品', 'is_correct': True,
                                 'explanation': '第二十条明确禁止针对特定客户非公开销售优于同类客户的产品。'},
                                {'id': 'D', 'text': '在销售专区进行录音录像', 'is_correct': False,
                                 'explanation': '第三十九条规定应落实销售专区录音录像，属于合规操作。'},
                                {'id': 'E', 'text': '代销持有金融牌照机构发行的基金产品', 'is_correct': False,
                                 'explanation': '第二十条禁止代销未持牌机构产品，代销持牌机构产品是允许的。'}],
                    'overall_explanation': '第二十条明确禁止销售未经审批产品、非公开优待特定客户、代销无牌照机构产品等行为。风险提示和录音录像是合规要求，不属于禁止行为。'},
                   {'type': 'multiple_choice', 'question_text': '根据《准则》，以下哪些行为体现了‘履职遵纪’的要求？',
                    'options': [{'id': 'A', 'text': '主动报告与亲属在机构内交易的潜在利益冲突', 'is_correct': True,
                                 'explanation': '第二十八条要求在存在潜在利益冲突时主动说明情况。'},
                                {'id': 'B', 'text': '接受客户赠送的价值超过商业习惯允许范围的礼品', 'is_correct': False,
                                 'explanation': '第三十二条严禁收受价值过高的礼品，属于违规行为。'},
                                {'id': 'C', 'text': '在公务出差中选择超标酒店住宿', 'is_correct': False,
                                 'explanation': '第二十二条要求严格执行住宿标准，超标属于违反财务管理规定。'},
                                {'id': 'D', 'text': '任职期间主动申请回避与亲属在同一部门工作', 'is_correct': True,
                                 'explanation': '第三十条要求在出现回避情形时主动提出回避申请。'},
                                {'id': 'E', 'text': '利用职务便利为近亲属提供明显优惠的贷款条件', 'is_correct': False,
                                 'explanation': '第二十九条严禁通过近亲属以明显优于正常商业条件与机构交易。'}],
                    'overall_explanation': '履职遵纪包括主动报告利益冲突、实施履职回避等合规行为。收受贵重礼品、超标消费、违规优待亲属均违反相关纪律要求。'},
                   {'type': 'multiple_choice', 'question_text': '在维护国家金融安全方面，银行业从业人员应履行哪些义务？',
                    'options': [{'id': 'A', 'text': '积极配合监管机构的现场检查', 'is_correct': True,
                                 'explanation': '第四十一条要求从业人员依法接受并配合监管工作。'},
                                {'id': 'B', 'text': '落实大额和可疑交易报告制度', 'is_correct': True,
                                 'explanation': '第四十二条明确从业人员应熟知并落实反洗钱报告义务。'},
                                {'id': 'C', 'text': '协助客户隐匿资产以逃避执法机关查扣', 'is_correct': False,
                                 'explanation': '第四十三条禁止协助客户隐匿、转移资产，必须依法协助执法。'},
                                {'id': 'D', 'text': '在重大公共事件中坚守岗位保障金融服务', 'is_correct': True,
                                 'explanation': '第四十五条要求在应急事件中服从安排、尽职履责。'},
                                {'id': 'E', 'text': '通过自媒体发布内部风控政策解读', 'is_correct': False,
                                 'explanation': '第四十六条严禁擅自通过自媒体等形式对外发布机构信息。'}],
                    'overall_explanation': '从业人员在金融安全方面的义务包括配合监管、反洗钱报告、协助执法、应急值守等，但不得擅自对外发布信息或协助客户规避法律。'},
                   {'type': 'multiple_choice', 'question_text': '关于客户权益保护，以下哪些做法符合《准则》要求？',
                    'options': [{'id': 'A', 'text': '对残障客户提供优先服务通道', 'is_correct': True,
                                 'explanation': '第三十七条要求尽可能为残障者提供便利，体现公平对待。'},
                                {'id': 'B', 'text': '因客户年龄较大而拒绝为其办理复杂业务', 'is_correct': False,
                                 'explanation': '第三十七条禁止因年龄等因素歧视客户，应公平提供服务。'},
                                {'id': 'C', 'text': '向客户隐瞒产品可能亏损的风险以促成销售', 'is_correct': False,
                                 'explanation': '第三十九条严禁隐瞒风险或进行虚假陈述，必须充分披露信息。'},
                                {'id': 'D', 'text': '耐心处理客户投诉并及时反馈', 'is_correct': True,
                                 'explanation': '第四十条要求坚持客户至上，认真处理投诉并作出有效反馈。'},
                                {'id': 'E', 'text': '在客户提出不合理要求时，耐心说明并争取理解', 'is_correct': True,
                                 'explanation': '第三十六条要求对不合理要求耐心说明，取得理解和谅解。'}],
                    'overall_explanation': '保护客户权益包括公平对待、充分披露、妥善处理投诉、满足合理需求并耐心解释不合理请求。任何形式的歧视或隐瞒风险均属违规。'}]}
# for sub in a['questions']:


b = json.dumps(a, indent=True, ensure_ascii=False)
print(b)
